### ISSUE TITLE
[INVESTIGATION] Fully jitted training loop

### ISSUE THREAD

**Issue by thomashirtz** [EdanToledo/Stoix#104]
### What do you want to investigate?

I have reviewed the codebase and noticed that, as far as I know, the entire pipeline is not encapsulated within a fully JIT-compiled loop. I suspect this might be due to the potential engineering challenges associated with implementing such a change

Questions:
- Potential Speedup: Can you provide an estimate of the potential speedup we might achieve by JIT-compiling the entire pipeline?
- Complexity of Changes: What is the complexity of the changes required to implement this JIT compilation?

I am currently testing with an environment where I am achieving approximately 6000 steps per second. I would like to understand if the potential performance gain may justifies the engineering effort

Thank you!

**Comment by EdanToledo** [comment]
When you say the entire pipeline, are you referring to how I split it into training chunks based on the number of evaluations chosen? Other than that the entire training chunk and evaluations are all jitted. If this is what you are referring to, a very easy way to test if there would be any speed up through full entire jitting would be to comment out the evaluation code where we run it so only training occurs, set the number of evaluations to something reasonable like 20 so it splits training into 20 chunks. Run this and measure the wall clock time of the entire training. Then set the number of evaluations to something like 1 or 2 to largely increase the size of the training chunk and then measure the wall clock time. This would tell us if the splitting up causes large performance issues but I can't imagine it being large and certainly not enough to warrant changes however I'm always ready to eat my words with JAX.

**Comment by EdanToledo** [comment]
I'm currently at ICML, I might only be able to do this myself after Sunday. Although if I find the time I'll do it as soon as I can.

**Comment by thomashirtz** [comment]
> When you say the entire pipeline, are you referring to how I split it into training chunks based on the number of evaluations chosen? Other than that the entire training chunk and evaluations are all jitted. If this is what you are referring to, a very easy way to test if there would be any speed up through full entire jitting would be to comment out the evaluation code where we run it so only training occurs, set the number of evaluations to something reasonable like 20 so it splits training into 20 chunks. Run this and measure the wall clock time of the entire training. Then set the number of evaluations to something like 1 or 2 to largely increase the size of the training chunk and then measure the wall clock time. This would tell us if the splitting up causes large performance issues but I can't imagine it being large and certainly not enough to warrant changes however I'm always ready to eat my words with JAX.

Ok ! I'll try that 
I let you know (and append comment on this issue) if I find something interesting, in the meantime what you are saying make sense and I'll close it for now :)

Congrats for ICML 🎉
