### ISSUE TITLE
[BUG] Sebulba PPO Actor Steps per second incorrect

### ISSUE THREAD

**Issue by EdanToledo** [EdanToledo/Stoix#107]
### Describe the bug
Sebulba PPO Actor Steps per second incorrect. The steps_per_rollout is used incorrectly due to legacy anakin code.

**Comment by caineblood** [comment]
that is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.
