### ISSUE TITLE
[FEATURE] Log the trainer time

### ISSUE THREAD

**Issue by thomashirtz** [EdanToledo/Stoix#128]
### Feature description
When running experiments, I can keep track of the fps of the actor and the evaluator. However, what interests me the most in my case is the fps of the trainer (how many learning steps I have per second)

I would like to know how we can set stoix up in order to have this features. If you provide me guidelines, I can create the PR.

Current situation of the logging information in my version:
```
ACTOR - Steps per second: 21.900 | Episode length mean: 1.000 | Episode length std: 0.000 | Episode length min: 1.000 | Episode length max: 1.000 | Episode return mean: -0.059 | Episode return std: 0.235 | Episode return min: -1.000 | Episode return max: 0.000
TRAINER - Actor loss: 0.005 | Entropy: 0.637 | Value loss: 0.008
EVALUATOR - Steps per second: 346.916 | Episode length mean: 1.000 | Episode length std: 0.000 | Episode length min: 1.000 | Episode length max: 1.000 | Episode return mean: -0.065 | Episode return std: 0.247 | Episode return min: -1.000 | Episode return max: 0.000
```

**Comment by EdanToledo** [comment]
Okay so i've made the PR, it actually would be nice if you could review it just to double check my logic and let me know what you think.

**Comment by thomashirtz** [comment]
I just checked the PR, it looks good to me, more straightforward than I imagined :) Thanks a lot
