### ISSUE TITLE
[FEATURE] Include command-line interface

### ISSUE THREAD

**Issue by gregfurman** [EdanToledo/Stoix#39]
### Problem
In order to run a model, we need to specify the exact `.py` of the system model i.e `python stoix/systems/ff_ppo.py`. 

### Solution
It would be much easier if instead one could run `python stoix --model=ff_ppo` which would, in turn, kick off the training/eval. We can add a list of accepted/currently defined models such that `python stoix -m fake_model` would give an error. This can be backwards compatible with the current approach of specifying the exact file.

### Notes
Some approaches could be:
- Include this information in the hydra config and make it configurable via a `system=<?>` flag
- Create a CLI interface in a `stoix.py` file that can be used as a driver class to run everything else
- Write a separate CLI tool that can reside inside this as a sub-repo

**Comment by EdanToledo** [comment]
I'm gonna close this as this is not a priority right now and is not on the roadmap. In the future it might be useful for sure but to have a more focused issue list - its gonna be closed <3
